[build]
  command = "VITE_API_URL=https://dmcashield-agency.vercel.app npm run build"
  publish = "dist"
  directory = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.Cache-Control]
    value = "no-cache"